version: '3'

services:

  reciclavel-metal:
    build: ./reciclavel-metal
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://eu:SENHA@cluster0.t4wiie6.mongodb.net/reciclagem?retryWrites=true&w=majority
    networks:
      - minha-rede

reciclavel-papel:
    build: ./reciclavel-papel
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb+srv://eu:SENHA@cluster0.t4wiie6.mongodb.net/reciclagem?retryWrites=true&w=majority
    networks:
      - minha-rede

reciclavel-plastico:
    build: ./reciclavel-plastico
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb+srv://eu:SENHA@cluster0.t4wiie6.mongodb.net/reciclagem?retryWrites=true&w=majority
    networks:
      - minha-rede

reciclavel-vidro:
    build: ./reciclavel-vidro
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb+srv://eu:SENHA@cluster0.t4wiie6.mongodb.net/reciclagem?retryWrites=true&w=majority
    networks:
      - minha-rede
  

networks:
  minha-rede:
    driver: bridge